//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID_C { get; set; }
        public string Surename { get; set; }
        public string Name { get; set; }
        public string FamilyName { get; set; }
        public int Gender { get; set; }
    
        public virtual Gender Gender1 { get; set; }
    }
}
