//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentList
    {
        public int ID_CL { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int ID_O { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
