//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ComponentList = new HashSet<ComponentList>();
        }
    
        public int ID_O { get; set; }
        public string Name { get; set; }
        public int ID_Master { get; set; }
        public int ID_Client { get; set; }
        public int ID_Manager { get; set; }
        public int ID_PK { get; set; }
        public int Price { get; set; }
    
        public virtual ICollection<ComponentList> ComponentList { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual PersonalComputer PersonalComputer { get; set; }
    }
}
