//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.PersonalComputer = new HashSet<PersonalComputer>();
        }
    
        public int ID_T { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PersonalComputer> PersonalComputer { get; set; }
    }
}
